# This file was generated by GoReleaser. DO NOT EDIT.
cask "zentao-cli" do
  version "1.1.0+21.7"

  on_macos do
    on_arm do
      sha256 "91f2d6a65ef28c4cb0aad454ddab2bc812510a6684070878432bd7dd111a1697"
      url "https://github.com/windosx/zentao-cli/releases/download/v#{version}/zentao-cli-#{version}-darwin-arm64.tar.gz"
      rename "zentao-cli-1.1.0+21.7-darwin-arm64/zentao", "zentao"
    end
    on_intel do
      sha256 "922217f03656ebebf2e92f4bc5418652cbc1d003f4b83e9d07a3a5a539ff4eb1"
      url "https://github.com/windosx/zentao-cli/releases/download/v#{version}/zentao-cli-#{version}-darwin-amd64.tar.gz"
      rename "zentao-cli-1.1.0+21.7-darwin-amd64/zentao", "zentao"
    end
  end
  on_linux do
    on_arm do
      sha256 "401a26a80ed80fc2b646754ee6bed3f3c6c485c9bfb324ea2b5939f0e099387d"
      url "https://github.com/windosx/zentao-cli/releases/download/v#{version}/zentao-cli-#{version}-linux-arm64.tar.gz"
      rename "zentao-cli-1.1.0+21.7-linux-arm64/zentao", "zentao"
    end
    on_intel do
      sha256 "0e34379588d7c7e99f38f9a7e0164643b4d00fa0288b48a64dd2248817400ffd"
      url "https://github.com/windosx/zentao-cli/releases/download/v#{version}/zentao-cli-#{version}-linux-amd64.tar.gz"
      rename "zentao-cli-1.1.0+21.7-linux-amd64/zentao", "zentao"
    end
  end

  name "zentao-cli"
  desc "ZenTao PMS CLI and Go SDK for AI agents and modern developers"
  homepage "https://github.com/windosx/zentao-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zentao"

  # No zap stanza required
end
