# This file was generated by GoReleaser. DO NOT EDIT.
cask "zentao-cli" do
  version "1.2.1+21.7"

  on_macos do
    on_arm do
      sha256 "1477f2d571802be4a3705d721740849b1180b3b227d5520112cb5b8d20b415c1"
      url "https://github.com/windosx/zentao-cli/releases/download/v#{version}/zentao-cli-#{version}-darwin-arm64.tar.gz"
      rename "zentao-cli-1.2.1+21.7-darwin-arm64/zentao", "zentao"
    end
    on_intel do
      sha256 "b1fb5956f70264a26dd84d57b80ce512edba5be98e207d5924339e02b4d3ee71"
      url "https://github.com/windosx/zentao-cli/releases/download/v#{version}/zentao-cli-#{version}-darwin-amd64.tar.gz"
      rename "zentao-cli-1.2.1+21.7-darwin-amd64/zentao", "zentao"
    end
  end
  on_linux do
    on_arm do
      sha256 "52cc9b9b03a19022f6df6a41d1c66abb03963e789b87d86b7d095e61b7246f2a"
      url "https://github.com/windosx/zentao-cli/releases/download/v#{version}/zentao-cli-#{version}-linux-arm64.tar.gz"
      rename "zentao-cli-1.2.1+21.7-linux-arm64/zentao", "zentao"
    end
    on_intel do
      sha256 "3f6425a380908dfbeb7499f8781bdbbefbfb5f6cd7a0c3076ce272ec662afa3d"
      url "https://github.com/windosx/zentao-cli/releases/download/v#{version}/zentao-cli-#{version}-linux-amd64.tar.gz"
      rename "zentao-cli-1.2.1+21.7-linux-amd64/zentao", "zentao"
    end
  end

  name "zentao-cli"
  desc "ZenTao PMS CLI and Go SDK for AI agents and modern developers"
  homepage "https://github.com/windosx/zentao-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zentao"

  # No zap stanza required
end
