# This file was generated by GoReleaser. DO NOT EDIT.
cask "zentao-cli" do
  version "1.1.0+21.7"

  on_macos do
    on_arm do
      sha256 "8cd508c686d2d17b6b44e7c3baa9676e9f3e4860064fdf5af57eb7a5880e2e7a"
      url "https://github.com/windosx/zentao-cli/releases/download/v#{version}/zentao-cli-#{version}-darwin-arm64.tar.gz"
      rename "zentao-cli-1.1.0+21.7-darwin-arm64/zentao", "zentao"
    end
    on_intel do
      sha256 "521dda74672850a4eb7fdc698dc9865ea4ae849189fa55c8093ee7ffbec6cd6c"
      url "https://github.com/windosx/zentao-cli/releases/download/v#{version}/zentao-cli-#{version}-darwin-amd64.tar.gz"
      rename "zentao-cli-1.1.0+21.7-darwin-amd64/zentao", "zentao"
    end
  end
  on_linux do
    on_arm do
      sha256 "a2698231a72a3778bfa540153bc9a7199b856df9117fe4f40429459e569bd6aa"
      url "https://github.com/windosx/zentao-cli/releases/download/v#{version}/zentao-cli-#{version}-linux-arm64.tar.gz"
      rename "zentao-cli-1.1.0+21.7-linux-arm64/zentao", "zentao"
    end
    on_intel do
      sha256 "c9d1ce9a0cf1b17fe740e9289c962c532f1b94b084e50056fa5101097d739751"
      url "https://github.com/windosx/zentao-cli/releases/download/v#{version}/zentao-cli-#{version}-linux-amd64.tar.gz"
      rename "zentao-cli-1.1.0+21.7-linux-amd64/zentao", "zentao"
    end
  end

  name "zentao-cli"
  desc "ZenTao PMS CLI and Go SDK for AI agents and modern developers"
  homepage "https://github.com/windosx/zentao-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zentao"

  # No zap stanza required
end
